language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: iUxYmTCmyM8shKv3fGmGEqWF7T6I7YUmYD9t7taXxrEgRvIMrpgj4UT398TfqOsdU7vXGDdvBmtnehgtQ9/Pzds7KHoevMFrJ1gsr9SRVOUtD5FzVB8gGQGvsR8znfTERJmYy0xHMNrGiJOWbgnQmxO7JihKP+G7198nXnwDuZg=
  - secure: ba3tCY03anw9uV4FYXvOBoN1iKJRPtrWqj5bpSQoaM04sFKwQhbZJGn2sv5X/gUUBh1F/hSnWEvIfD+I1UpI6v/HT9+eNQguiOLXOgd+BRdyarzg/zg1R52SmUCQ/pXpEjzIRsAInD0CPDA+9BBrePJXN0vjf2WchkDwzoh7WFU=
  matrix:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=chrome BROWSER_VERSION=35
  - BROWSER_NAME=chrome BROWSER_VERSION=34
  - BROWSER_NAME=firefox BROWSER_VERSION=latest
  - BROWSER_NAME=firefox BROWSER_VERSION=30
  - BROWSER_NAME=firefox BROWSER_VERSION=29
  - BROWSER_NAME=opera BROWSER_VERSION=latest
  - BROWSER_NAME=opera BROWSER_VERSION=11
  - BROWSER_NAME=safari BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=7
  - BROWSER_NAME=safari BROWSER_VERSION=6
  - BROWSER_NAME=safari BROWSER_VERSION=5
  - BROWSER_NAME=ie BROWSER_VERSION=11
  - BROWSER_NAME=ie BROWSER_VERSION=10
  - BROWSER_NAME=ie BROWSER_VERSION=9
  - BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - BROWSER_NAME=iphone BROWSER_VERSION=7.0
  - BROWSER_NAME=iphone BROWSER_VERSION=6.1
